Update from PowerShell 6.0.4 to 7.2.3
Update Microsoft.PowerShell.SDK to 7.2.3

Have to explicitly load the Microsoft.Management.Infrastructure.dll to
avoid an error creating the PowerShell runspace in
PowerShellConsoleHost.CreateInitialSessionState.

System.IO.FileLoadException: Could not load file or assembly
'Microsoft.Management.Infrastructure, Version=1.0.0.0, Culture=neutral,
PublicKeyToken=31bf3856ad364e35'. A strongly-named assembly is required.
(0x80131044)
File name: 'Microsoft.Management.Infrastructure, Version=1.0.0.0,
Culture=neutral, PublicKeyToken=31bf3856ad364e35'
 ---> System.IO.FileLoadException: A strongly-named assembly is required.
(0x80131044)
   at System.Reflection.RuntimeAssembly.GetExportedTypes()
   at System.Reflection.Assembly.get_ExportedTypes()
   at System.Management.Automation.Runspaces.PSSnapInHelpers.
GetAssemblyTypes(Assembly assembly, String name)