Support VS Mac 8.5
VS Mac 8.5 uses NuGet 5.4 whilst the addin was using NuGet 5.3 which
resulted in a type load exception on opening the NuGet Package Mangaer
Console window:

System.TypeLoadException: Could not load type of field 'NuGetConsole.Host.PowerShell.InstalledPackageEnumerator+<OrderPackagesForPackagesConfigAsync>d__9:<packagesToSort>5__3' (10) due to: Could not load file or assembly 'NuGet.Resolver, Version=5.3.0.3, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies.