Support Visual Studio for Mac 17.4
The ConsoleInputEventArgs class is no longer public in VS Mac.
The vsmac console external repository now includes this class.

Fix build error in EnvDTE Document class:

Error CS0118: 'Windows' is a namespace but is used like a type

Prefix the Windows type with its namespace to fix the clash.