Support NuGet 4.8 in Visual Studio for Mac 7.7.2
The Manage Packages dialog would not be displayed in Visual Studio
for Mac 7.7.2.21 due to an API change in the NuGet addin.

System.MissingMethodException: Method not found: void
MonoDevelop.PackageManagement.NuGetProjectContext..ctor()