Support VS Mac 8.8
Update NuGet libraries to 5.8.
Fix problem with System.Collections.Immutable causing build to
fail with:

Error CS1705: Assembly 'MonoDevelop.Core' with identity
'MonoDevelop.Core, Version=2.6.0.0, Culture=neutral, PublicKeyToken=3ead7498f347467b'
uses 'System.Collections.Immutable, Version=5.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
which has a higher version than referenced assembly
'System.Collections.Immutable' with identity
'System.Collections.Immutable, Version=1.2.3.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
(CS1705) (MonoDevelop.PackageManagement.Extensions)

At build time the System.Collections.Immutable.dll was being taken
from:
~/.nuget/packages/system.collections.immutable/1.5.0/lib/netstandard2.0/System.Collections.Immutable.dll

To fix this the extensions project now has a PackageReference to
System.Collections.Immutable 5.0 and the assembly reference has
been removed and the immutable .dll has been removed from the Lib
directory. It seemed that the StreamJsonRpc PackageReference was
including the older immutable dll and the directly referenced one
was ignored.