Support Visual Studio for Mac 8.6
StreamJsonRpc was updated in VS Mac 8.6 and there was an API change
which caused the NuGet extensions addin to error on opening the
NuGet Package Manager Console:

System.MissingMethodException: Method not found: Newtonsoft.Json.JsonSerializer StreamJsonRpc.JsonRpc.get_JsonSerializer()

Updated the binaries to VS Mac 8.6.0.4243 (preview 2).

Fixes #36