Support NuGet 4.7 in Visual Studio for Mac 7.7.0.1738
Visual Studio for Mac 7.7.0.1738 release on the beta channel uses
NuGet 4.7. The NuGet extensions addin's package console extension
would not initialize and an IDE log error was reported:

System.TypeLoadException: VTable setup of type
MonoDevelop.PackageManagement.ConsoleHostSolutionManager failed

The NuGet extension addin now works with NuGet 4.7 being used in
MonoDevelop 7.7.