Fix build error in EnvDTE document class
Error CS0118: 'Windows' is a namespace but is used like a type

Prefix the Windows type with its namespace to fix the clash.